USE riada_db;

DROP TEMPORARY TABLE IF EXISTS tmp_test_results;
CREATE TEMPORARY TABLE tmp_test_results (
    test_id     VARCHAR(10)  NOT NULL,
    test_name   VARCHAR(160) NOT NULL,
    status      ENUM('OK','FAIL') NOT NULL,
    details     VARCHAR(255) NOT NULL,
    PRIMARY KEY (test_id)
) ENGINE=MEMORY;

SET @v_members := (SELECT COUNT(*) FROM members);
INSERT INTO tmp_test_results VALUES ('T01', 'members row count', IF(@v_members = 120, 'OK', 'FAIL'), CONCAT('members=', @v_members));

SET @v_employees := (SELECT COUNT(*) FROM employees);
INSERT INTO tmp_test_results VALUES ('T02', 'employees row count', IF(@v_employees = 20, 'OK', 'FAIL'), CONCAT('employees=', @v_employees));

SET @v_contract_active := (SELECT COUNT(*) FROM contracts WHERE status = 'active');
SET @v_contract_suspended := (SELECT COUNT(*) FROM contracts WHERE status = 'suspended');
SET @v_contract_expired := (SELECT COUNT(*) FROM contracts WHERE status = 'expired');
SET @v_contract_cancelled := (SELECT COUNT(*) FROM contracts WHERE status = 'cancelled');
INSERT INTO tmp_test_results
VALUES (
    'T03',
    'contracts status distribution',
    IF(@v_contract_active = 84 AND @v_contract_suspended = 12 AND @v_contract_expired = 18 AND @v_contract_cancelled = 6, 'OK', 'FAIL'),
    CONCAT('a=', @v_contract_active, ',s=', @v_contract_suspended, ',e=', @v_contract_expired, ',c=', @v_contract_cancelled)
);

SET @v_suspended_bad := (
    SELECT COUNT(*)
    FROM contracts
    WHERE status = 'suspended'
      AND freeze_start_date IS NULL
);
INSERT INTO tmp_test_results
VALUES ('T04', 'suspended contracts require freeze_start_date', IF(@v_suspended_bad = 0, 'OK', 'FAIL'), CONCAT('bad_rows=', @v_suspended_bad));

SET @v_edge_overdue := (
    SELECT COUNT(*)
    FROM invoices i
    JOIN contracts c ON c.id = i.contract_id
    WHERE c.member_id = 1
      AND i.status = 'overdue'
      AND i.due_date = DATE_SUB(CURDATE(), INTERVAL 30 DAY)
);
INSERT INTO tmp_test_results VALUES ('T05', 'edge overdue invoice exists for member 1', IF(@v_edge_overdue >= 1, 'OK', 'FAIL'), CONCAT('rows=', @v_edge_overdue));

SET @v_blank_invoice_numbers := (SELECT COUNT(*) FROM invoices WHERE invoice_number IS NULL OR invoice_number = '');
INSERT INTO tmp_test_results VALUES ('T06', 'invoice numbers generated by trigger', IF(@v_blank_invoice_numbers = 0, 'OK', 'FAIL'), CONCAT('blank=', @v_blank_invoice_numbers));

CALL sp_CheckAccess(1, 1, @decision_member1);
INSERT INTO tmp_test_results VALUES ('T07', 'sp_CheckAccess member 1 overdue denied', IF(@decision_member1 = 'denied', 'OK', 'FAIL'), CONCAT('decision=', @decision_member1));

CALL sp_CheckAccess(2, 2, @decision_member2);
INSERT INTO tmp_test_results VALUES ('T08', 'sp_CheckAccess member 2 granted', IF(@decision_member2 = 'granted', 'OK', 'FAIL'), CONCAT('decision=', @decision_member2));

CALL sp_CheckAccess(999999, 1, @decision_unknown_member);
INSERT INTO tmp_test_results VALUES ('T09', 'sp_CheckAccess unknown member denied', IF(@decision_unknown_member = 'denied', 'OK', 'FAIL'), CONCAT('decision=', @decision_unknown_member));

CALL sp_CheckAccessGuest(4, 4, 2, @decision_banned_guest);
INSERT INTO tmp_test_results VALUES ('T10', 'sp_CheckAccessGuest banned guest denied', IF(@decision_banned_guest = 'denied', 'OK', 'FAIL'), CONCAT('decision=', @decision_banned_guest));

INSERT INTO access_log (member_id, club_id, accessed_at, access_status, denial_reason)
VALUES (11, 1, NOW(3), 'granted', NULL);
CALL sp_CheckAccessGuest(5, 11, 1, @decision_active_guest);
INSERT INTO tmp_test_results VALUES ('T11', 'sp_CheckAccessGuest active guest granted', IF(@decision_active_guest = 'granted', 'OK', 'FAIL'), CONCAT('decision=', @decision_active_guest));

SET @v_failed_without_error := (
    SELECT COUNT(*)
    FROM payments
    WHERE status = 'failed'
      AND (error_code IS NULL OR TRIM(error_code) = '')
);
INSERT INTO tmp_test_results VALUES ('T12', 'failed payments contain error_code', IF(@v_failed_without_error = 0, 'OK', 'FAIL'), CONCAT('bad_rows=', @v_failed_without_error));

SET @v_denied_member_without_reason := (
    SELECT COUNT(*)
    FROM access_log
    WHERE access_status = 'denied'
      AND (denial_reason IS NULL OR TRIM(denial_reason) = '')
);
INSERT INTO tmp_test_results VALUES ('T13', 'denied member accesses have reason', IF(@v_denied_member_without_reason = 0, 'OK', 'FAIL'), CONCAT('bad_rows=', @v_denied_member_without_reason));

SET @v_denied_guest_without_reason := (
    SELECT COUNT(*)
    FROM guest_access_log
    WHERE access_status = 'denied'
      AND (denial_reason IS NULL OR TRIM(denial_reason) = '')
);
INSERT INTO tmp_test_results VALUES ('T14', 'denied guest accesses have reason', IF(@v_denied_guest_without_reason = 0, 'OK', 'FAIL'), CONCAT('bad_rows=', @v_denied_guest_without_reason));

SET @v_multi_active_guest_sponsors := (
    SELECT COUNT(*)
    FROM (
        SELECT sponsor_member_id
        FROM guests
        WHERE status = 'active'
          AND sponsor_member_id IS NOT NULL
        GROUP BY sponsor_member_id
        HAVING COUNT(*) > 1
    ) t
);
INSERT INTO tmp_test_results VALUES ('T15', 'one active guest per sponsor rule', IF(@v_multi_active_guest_sponsors = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_multi_active_guest_sponsors));

SET @v_underage_members := (
    SELECT COUNT(*)
    FROM members
    WHERE date_of_birth > DATE_SUB(CURDATE(), INTERVAL 16 YEAR)
);
INSERT INTO tmp_test_results VALUES ('T16', 'member minimum age rule', IF(@v_underage_members = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_underage_members));

INSERT INTO invoices (
    contract_id, invoice_number, issued_on, due_date, billing_period_start, billing_period_end, amount_excl_tax, vat_rate, status, amount_paid
)
VALUES (
    2, '', CURDATE(), DATE_ADD(CURDATE(), INTERVAL 15 DAY), DATE_FORMAT(CURDATE(), '%Y-%m-01'), LAST_DAY(CURDATE()), 12.00, 0.2100, 'issued', 0.00
);
SET @v_invoice_test_id := LAST_INSERT_ID();
SET @v_invoice_test_amount := (SELECT amount_incl_tax FROM invoices WHERE id = @v_invoice_test_id);
INSERT INTO payments (
    invoice_id, paid_at, amount, status, payment_method, transaction_reference, error_code, attempt_count
)
VALUES (
    @v_invoice_test_id, NOW(3), @v_invoice_test_amount, 'succeeded', 'credit_card', CONCAT('TEST-PAY-', @v_invoice_test_id), NULL, 1
);
SET @v_invoice_test_status := (SELECT status FROM invoices WHERE id = @v_invoice_test_id);
INSERT INTO tmp_test_results VALUES ('T17', 'payment trigger updates invoice status to paid', IF(@v_invoice_test_status = 'paid', 'OK', 'FAIL'), CONCAT('status=', @v_invoice_test_status));
DELETE FROM payments WHERE invoice_id = @v_invoice_test_id;
DELETE FROM invoice_lines WHERE invoice_id = @v_invoice_test_id;
DELETE FROM invoices WHERE id = @v_invoice_test_id;

SET @v_overbooked_sessions := (
    SELECT COUNT(*)
    FROM class_sessions cs
    JOIN courses c ON c.id = cs.course_id
    LEFT JOIN (
        SELECT session_id, COUNT(*) AS confirmed_count
        FROM bookings
        WHERE status = 'confirmed'
        GROUP BY session_id
    ) b ON b.session_id = cs.id
    WHERE COALESCE(b.confirmed_count, 0) > c.max_capacity
       OR cs.enrolled_count > c.max_capacity
);
INSERT INTO tmp_test_results VALUES ('T18', 'booking capacity rule enforced', IF(@v_overbooked_sessions = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_overbooked_sessions));

SET @v_custom_indexes := (
    SELECT COUNT(DISTINCT index_name)
    FROM information_schema.statistics
    WHERE table_schema = DATABASE()
      AND index_name IN (
          'idx_clubs_city_status',
          'idx_members_city_status',
          'idx_members_goal_source',
          'idx_contracts_status_end_date',
          'idx_contracts_member_status_start',
          'idx_contract_options_contract_dates',
          'idx_contract_options_contract_removed',
          'idx_invoices_status_due_date',
          'idx_invoices_contract_period_status',
          'idx_payments_status_paid_at',
          'idx_access_log_club_status_at',
          'idx_guest_access_log_club_status_at',
          'idx_class_sessions_club_start',
          'idx_maintenance_status_priority_reported'
      )
);
INSERT INTO tmp_test_results VALUES ('T19', 'custom index set exists', IF(@v_custom_indexes = 14, 'OK', 'FAIL'), CONCAT('indexes=', @v_custom_indexes));

SET @v_roles := (
    SELECT COUNT(DISTINCT FROM_USER)
    FROM mysql.role_edges
    WHERE FROM_USER IN ('role_gate_access', 'role_billing_ops', 'role_data_protection')
      AND TO_USER IN ('portique_user', 'billing_user', 'dpo_user')
);
SET @v_default_roles := (
    SELECT COUNT(*)
    FROM mysql.default_roles
    WHERE user IN ('portique_user', 'billing_user', 'dpo_user')
);
INSERT INTO tmp_test_results VALUES ('T20', 'security roles and default role mappings', IF(@v_roles = 3 AND @v_default_roles = 3, 'OK', 'FAIL'), CONCAT('roles=', @v_roles, ',defaults=', @v_default_roles));

SET @v_legacy_tables := (
    SELECT COUNT(*)
    FROM information_schema.tables
    WHERE table_schema = DATABASE()
      AND table_name IN (
          'membres',
          'abonnements',
          'options_services',
          'contrats_adhesion',
          'factures',
          'journal_acces',
          'sessions_cours',
          'equipements',
          'invites',
          'maintenance'
      )
);
INSERT INTO tmp_test_results VALUES ('T21', 'legacy table names absent', IF(@v_legacy_tables = 0, 'OK', 'FAIL'), CONCAT('legacy_tables=', @v_legacy_tables));

SET @v_club1_previous_status := (SELECT operational_status FROM clubs WHERE id = 1);
UPDATE clubs SET operational_status = 'temporarily_closed' WHERE id = 1;
CALL sp_CheckAccess(2, 1, @decision_closed_club);
INSERT INTO tmp_test_results VALUES ('T22', 'sp_CheckAccess denies temporarily closed club', IF(@decision_closed_club = 'denied', 'OK', 'FAIL'), CONCAT('decision=', @decision_closed_club));
UPDATE clubs SET operational_status = @v_club1_previous_status WHERE id = 1;

INSERT INTO access_log (member_id, club_id, accessed_at, access_status, denial_reason)
VALUES (2, 1, NOW(3), 'granted', NULL);
CALL sp_CheckAccessGuest(1, 2, 1, @decision_guest_wrong_sponsor);
INSERT INTO tmp_test_results VALUES ('T23', 'sp_CheckAccessGuest denies wrong sponsor companion', IF(@decision_guest_wrong_sponsor = 'denied', 'OK', 'FAIL'), CONCAT('decision=', @decision_guest_wrong_sponsor));

SET @v_invalid_session_instructors := (
    SELECT COUNT(*)
    FROM class_sessions cs
    JOIN employees e ON e.id = cs.instructor_id
    WHERE e.role NOT IN ('instructor', 'intern')
       OR e.club_id <> cs.club_id
);
INSERT INTO tmp_test_results VALUES ('T24', 'class sessions instructor role and club integrity', IF(@v_invalid_session_instructors = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_invalid_session_instructors));

SET @v_booking_policy_violations := (
    SELECT COUNT(*)
    FROM bookings b
    JOIN class_sessions cs ON cs.id = b.session_id
    JOIN clubs cl ON cl.id = cs.club_id
    JOIN members m ON m.id = b.member_id
    LEFT JOIN contracts c
           ON c.member_id = b.member_id
          AND c.status = 'active'
          AND (c.end_date IS NULL OR c.end_date >= DATE(cs.starts_at))
    LEFT JOIN subscription_plans sp ON sp.id = c.plan_id
    WHERE b.status IN ('confirmed', 'waitlisted')
      AND (
          cl.operational_status <> 'open'
          OR m.status <> 'active'
          OR c.id IS NULL
          OR (sp.limited_club_access = 1 AND c.home_club_id <> cs.club_id)
          OR cs.starts_at <= b.booked_at
      )
);
INSERT INTO tmp_test_results VALUES ('T25', 'booking policy integrity on active data', IF(@v_booking_policy_violations = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_booking_policy_violations));

SET @v_contract_policy_violations := (
    SELECT COUNT(*)
    FROM contracts c
    WHERE (
            c.status = 'suspended'
            AND (c.freeze_start_date IS NULL OR c.freeze_end_date IS NULL)
          )
       OR (
            c.status = 'cancelled'
            AND (
                c.cancelled_on IS NULL
                OR c.cancellation_reason IS NULL
                OR TRIM(c.cancellation_reason) = ''
            )
          )
       OR (
            c.status = 'active'
            AND (
                c.freeze_start_date IS NOT NULL
                OR c.freeze_end_date IS NOT NULL
                OR c.cancelled_on IS NOT NULL
            )
          )
);
INSERT INTO tmp_test_results VALUES ('T26', 'contract status metadata integrity', IF(@v_contract_policy_violations = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_contract_policy_violations));

SET @v_active_guest_policy_violations := (
    SELECT COUNT(*)
    FROM guests g
    LEFT JOIN members m ON m.id = g.sponsor_member_id
    LEFT JOIN (
        SELECT DISTINCT c.member_id
        FROM contracts c
        JOIN subscription_plans sp ON sp.id = c.plan_id
        WHERE c.status = 'active'
          AND (c.end_date IS NULL OR c.end_date >= CURDATE())
          AND sp.duo_pass_allowed = 1
    ) dq ON dq.member_id = g.sponsor_member_id
    WHERE g.status = 'active'
      AND (
          g.sponsor_member_id IS NULL
          OR m.status <> 'active'
          OR dq.member_id IS NULL
      )
);
INSERT INTO tmp_test_results VALUES ('T27', 'active guest sponsor duo-pass integrity', IF(@v_active_guest_policy_violations = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_active_guest_policy_violations));

SET @v_maintenance_policy_violations := (
    SELECT COUNT(*)
    FROM maintenance_tickets mt
    LEFT JOIN employees e ON e.id = mt.technician_id
    WHERE (
            mt.status = 'resolved'
            AND mt.resolved_at IS NULL
          )
       OR (
            mt.status <> 'resolved'
            AND mt.resolved_at IS NOT NULL
          )
       OR (
            mt.status IN ('assigned', 'in_progress', 'resolved')
            AND mt.technician_id IS NULL
          )
       OR (
            mt.technician_id IS NOT NULL
            AND (e.id IS NULL OR e.role NOT IN ('technician', 'manager', 'management'))
          )
);
INSERT INTO tmp_test_results VALUES ('T28', 'maintenance lifecycle and technician integrity', IF(@v_maintenance_policy_violations = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_maintenance_policy_violations));

SET @v_session_policy_violations := (
    SELECT COUNT(*)
    FROM class_sessions cs
    JOIN courses c ON c.id = cs.course_id
    WHERE cs.starts_at <= NOW(3)
       OR cs.starts_at > NOW(3) + INTERVAL 180 DAY
       OR cs.duration_minutes <> c.duration_minutes
       OR cs.enrolled_count > c.max_capacity
);
INSERT INTO tmp_test_results VALUES ('T29', 'class session timing/capacity integrity', IF(@v_session_policy_violations = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_session_policy_violations));

SET @v_payment_policy_violations := (
    SELECT COUNT(*)
    FROM payments p
    JOIN invoices i ON i.id = p.invoice_id
    WHERE (
            p.status = 'failed'
            AND (p.error_code IS NULL OR TRIM(p.error_code) = '')
          )
       OR (
            p.status <> 'failed'
            AND p.error_code IS NOT NULL
            AND TRIM(p.error_code) <> ''
          )
       OR (
            p.status IN ('succeeded', 'refunded')
            AND (p.transaction_reference IS NULL OR TRIM(p.transaction_reference) = '')
          )
       OR (
            p.status = 'succeeded'
            AND i.status = 'cancelled'
          )
       OR (
            p.paid_at > NOW(3) + INTERVAL 1 DAY
          )
);
INSERT INTO tmp_test_results VALUES ('T30', 'payment status/reference/date integrity', IF(@v_payment_policy_violations = 0, 'OK', 'FAIL'), CONCAT('violations=', @v_payment_policy_violations));

SELECT * FROM tmp_test_results ORDER BY test_id;

SELECT
    COUNT(*) AS total_tests,
    SUM(CASE WHEN status = 'OK' THEN 1 ELSE 0 END) AS passed_tests,
    SUM(CASE WHEN status = 'FAIL' THEN 1 ELSE 0 END) AS failed_tests,
    ROUND(100 * SUM(CASE WHEN status = 'OK' THEN 1 ELSE 0 END) / COUNT(*), 2) AS pass_rate_pct
FROM tmp_test_results;
